name: CI - ASP.NET Core API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.0.x"
  PROJECT_PATH: "1-Presentation/Bernhoeft.GRT.Teste.Api/Bernhoeft.GRT.Teste.Api.csproj"
  TEST_PROJECT_PATH: "0-Tests/Bernhoeft.GRT.Teste.IntegrationTests/Bernhoeft.GRT.Teste.IntegrationTests.csproj"
  PUBLISH_DIR: "publish"

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # RESTORE (tem que restaurar para Release)
      - name: Restore dependencies
        run: dotnet restore $PROJECT_PATH

      # BUILD (sem --no-restore senão quebra por causa dos diretórios customizados)
      - name: Build API
        run: dotnet build $PROJECT_PATH --configuration Release

      # TESTS (não usa --no-build porque seus projetos têm paths customizados)
      - name: Run unit tests
        run: dotnet test $TEST_PROJECT_PATH --configuration Release --verbosity normal

      # PUBLISH (sem --no-build)
      - name: Publish API
        run: dotnet publish $PROJECT_PATH -c Release -o $PUBLISH_DIR

      # ARTIFACT
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ env.PUBLISH_DIR }}
