name: CI - ASP.NET Core API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.0.x"
  PROJECT_PATH: "1-Presentation/Bernhoeft.GRT.Api/Bernhoeft.GRT.Api.csproj"
  TEST_PROJECT_PATH: "0-Tests/Bernhoeft.GRT.Tests/Bernhoeft.GRT.Tests.csproj"
  PUBLISH_DIR: "publish"

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Clone do repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore
      - name: Restore dependencies
        run: dotnet restore $env:PROJECT_PATH

      # Build
      - name: Build API
        run: dotnet build $env:PROJECT_PATH --configuration Release --no-restore

      # Testes
      - name: Run unit tests
        continue-on-error: false
        run: dotnet test $env:TEST_PROJECT_PATH --configuration Release --no-build --verbosity normal

      # Publish para produção
      - name: Publish API
        run: dotnet publish $env:PROJECT_PATH -c Release -o $env:PUBLISH_DIR --no-build

      # Artefato final para deploy (IIS, Docker, Azure etc.)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ env.PUBLISH_DIR }}
